import { Router } from 'express';
import authRoutes from './auth.routes';
import calendarRoutes from './calendar.routes';
import dashboardRoutes from './dashboard.routes';
import profileRoutes from './profile.routes';
import routinesRoutes from './routines.routes';
import statsRoutes from './stats.routes';
import goalsRoutes from './goals.routes';
import achievementsRoutes from './achievements.routes';
import journalRoutes from './journal.routes';
import notificationsRoutes from './notifications.routes';
import onboardingRoutes from './onboarding.routes';
import friendsRoutes from './friends.routes';
import usersRoutes from './users.routes';
import leaderboardsRoutes from './leaderboards.routes';
import routineBundlesRoutes from './routineBundles.routes';
import billingRoutes from './billing.routes';
import focusSessionsRoutes from './focusSessions.routes';
import calendarSyncRoutes from './calendarSync.routes';
import insightsRoutes from './insights.routes';
import feedbackRoutes from './feedback.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/routines', routinesRoutes);
router.use('/calendar', calendarRoutes);
router.use('/stats', statsRoutes);
router.use('/profile', profileRoutes);
router.use('/goals', goalsRoutes);
router.use('/achievements', achievementsRoutes);
router.use('/journal', journalRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/friends', friendsRoutes);
router.use('/users', usersRoutes);
router.use('/leaderboards', leaderboardsRoutes);
router.use('/routine-bundles', routineBundlesRoutes);
router.use('/billing', billingRoutes);
router.use('/focus-sessions', focusSessionsRoutes);
router.use('/calendar-sync', calendarSyncRoutes);
router.use('/calendar', calendarSyncRoutes);
router.use('/insights', insightsRoutes);
router.use('/', feedbackRoutes);

export default router;
